modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPL v3"
issueTrackerURL = "https://github.com/DoveCotMC/Tactical-Graphic-cards" #optional
[[mods]]
modId = "tactical_cards"
version = "1.1.0r-build-20230222"
displayName = "Tactical Graphic cards"
logoFile = "icon.png"
authors = "Arrokoth, Radekemia"
description = '''
This is a Mod, which added some Graphic cards.
'''